image: java:8-jdk

stages:
    - build

build:
    stage: build
    script: 
        - ls /opt
        - ./ant/bin/ant -find compile.xml
    artifacts:
        paths:
            - lib/wpilib/*.jar