image: java:8-jdk

stages:
    - build

build:
    stage: build
    script: 
        - mkdir /ant
        - wget --output-document="/ant/ant.zip" http://archive.apache.org/dist/ant/ant-current-bin.zip
        - unzip -j /ant/ant.zip -d /ant
        - ./ant/bin/ant -find compile.xml
    artifacts:
        paths:
            - lib/wpilib/*.jar